---
driver:
  name: docker
  use_sudo: false
  privileged: true

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true
  roles_path: ../ansible-os-hardening/
  playbook: default.yml
  ansible_extra_flags:
    - "--skip-tags=sysctl"

platforms:
  - name: ubuntu-16.04
    driver:
      image: quay.io/genevera/ubuntu:xenial-ansible
      provision_command:
        - "echo Acquire::Languages \"en_US\"; > /etc/apt.conf.d/docker-no-language; echo 'Acquire::http { Proxy \"http://apt-cacher-ng.docker:3142\"; };' > /etc/apt/apt.conf.d/01proxy && apt-get install initramfs-tools -y"
#  - name: centos-7
#    driver:
#      image: centos:7
#      privileged: true
#      run_command: /usr/sbin/init
  - name: debian-8
    driver:
      image: debian:8
      provision_command:
        - "echo Acquire::Languages \"en_US\"; > /etc/apt/apt.conf.d/docker-no-language; echo 'Acquire::http { Proxy \"http://apt-cacher-ng.docker:3142\"; };' >> /etc/apt/apt.conf.d/01proxy && apt-get update && apt-get -y upgrade"


# verifier:
#   name: inspec
#   sudo: true
#   inspec_tests:
#     - https://github.com/dev-sec/tests-os-hardening
 
suites:
- name: os_ansible_2.1.1.0
  provisioner:
    ansible_version: 2.1.1.0
- name: os_ansible_latest
